### ISSUE TITLE
SlackRtmClient gets EntityStreamException: Request too large

### ISSUE THREAD

**Issue by martinb3** [slack-scala-client/slack-scala-client#100]
Hi there -- I'm seeing these from the underlying Akka Http library:

```
[error] Exception in thread "main" akka.http.scaladsl.model.EntityStreamException: Request too large: Request was longer than the maximum of 8388608
[error] 	at akka.http.impl.util.ToStrict$$anon$1$$anon$3.onPush(package.scala:130)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
[error] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:407)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
[error] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
[error] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
[error] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[error] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[error] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

These are the versions I'm using:
```
sbt.version=1.2.8

scalaVersion := "2.12.1"
libraryDependencies += "com.typesafe" % "config" % "1.3.3"
libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.5.21"
libraryDependencies += "com.typesafe.akka" %% "akka-http-core" % "10.1.7"
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.7.1"
libraryDependencies += "org.json4s" %% "json4s-native" % "3.5.1"
libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.6.4"
libraryDependencies += "com.github.slack-scala-client" %% "slack-scala-client" % "0.2.6"
libraryDependencies += "org.scalaj" % "scalaj-http_2.12" % "2.3.0"
libraryDependencies += "org.apache.commons" % "commons-lang3" % "3.0.1"
```

I've tried a number of properties to try to make the limit larger, and tried specific values as well as `infinite`:
```
-Dakka.http.parsing.max-content-length=1024M
-Dakka.http.client.parsing.max-content-length=1024M
-Dakka.http.server.parsing.max-content-length=infinite
-Dplay.server.akka.http.parsing.max-content-length=infinite
-Dplay.server.akka.http.client.parsing.max-content-length=infinite
-Dplay.server.akka.http.server.parsing.max-content-length=infinite
-Dplay.client.akka.http.parsing.max-content-length=infinite
-Dplay.client.akka.http.client.parsing.max-content-length=infinite
-Dplay.client.akka.http.server.parsing.max-content-length=infinite
```

Do you have any tips or tricks for making that limit larger, or otherwise making the Akka HTTP library not crash? TIA!

**Comment by mccartney** [comment]
Not that I am aware of. A bit of googling shows other have similar problems (in non-Slack-related contexts).

Just to double check - are you submitting ~8MB worth of data?

**Comment by neitomic** [comment]
The error happens when Akka Http convert the response body into StrictEntity. 
For big Slack org, the response data can be bigger than 8MB.

The restriction can be changed with this config:
```
akka.http.parsing.max-to-strict-bytes = 128m
```
