### ISSUE TITLE
JsResultException on thread reply messages by bots

### ISSUE THREAD

**Issue by tmbull** [slack-scala-client/slack-scala-client#109]
I'm seeing a lot of `JsResultException` errors in my log. Here is an example:
```
16:02:46.376 [system-akka.actor.default-dispatcher-4] ERROR slack.rtm.SlackRtmConnectionActor - [SlackRtmClient] Error reading event: {"type":"message","subtype":"message_replied","hidden":true,"message":{"type":"message","subtype":"bot_message","text":":ubuntu: Preparing to restart system","ts":"1576165997.108800","username":"19004-Host","icons":{"image_48":"https://host/img.png"},"bot_id":"BERESWKDH","thread_ts":"1576165997.108800","reply_count":21,"reply_users_count":1,"latest_reply":"1576166566.113400","reply_users":["BERESWKDH"],"replies":[{"user":"BERESWKDH","ts":"1576166041.108900"},{"user":"BERESWKDH","ts":"1576166042.109100"},{"user":"BERESWKDH","ts":"1576166129.109300"},{"user":"BERESWKDH","ts":"1576166130.109500"},{"user":"BERESWKDH","ts":"1576166132.109700"},{"user":"BERESWKDH","ts":"1576166134.109900"},{"user":"BERESWKDH","ts":"1576166153.110100"},{"user":"BERESWKDH","ts":"1576166155.110300"},{"user":"BERESWKDH","ts":"1576166331.110500"},{"user":"BERESWKDH","ts":"1576166334.110700"},{"user":"BERESWKDH","ts":"1576166337.110900"},{"user":"BERESWKDH","ts":"1576166375.111100"},{"user":"BERESWKDH","ts":"1576166386.111300"},{"user":"BERESWKDH","ts":"1576166394.111500"},{"user":"BERESWKDH","ts":"1576166531.111800"},{"user":"BERESWKDH","ts":"1576166532.112000"},{"user":"BERESWKDH","ts":"1576166533.112200"},{"user":"BERESWKDH","ts":"1576166554.112400"},{"user":"BERESWKDH","ts":"1576166554.112600"},{"user":"BERESWKDH","ts":"1576166566.113200"},{"user":"BERESWKDH","ts":"1576166566.113400"}]},"channel":"G8C84QKDI","event_ts":"1576166566.113500","ts":"1576166566.113500"}
play.api.libs.json.JsResultException: JsResultException(errors:List((/message/user,List(JsonValidationError(List(error.path.missing),WrappedArray())))))
  at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
  at play.api.libs.json.JsError.fold(JsResult.scala:64)
  at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
  at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
  at play.api.libs.json.JsObject.as(JsValue.scala:124)
  at slack.models.package$$anon$9.reads(package.scala:322)
  at play.api.libs.json.JsValue.validate(JsValue.scala:17)
  at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
  at play.api.libs.json.JsObject.validate(JsValue.scala:124)
  at play.api.libs.json.JsReadable.as(JsReadable.scala:23)
  at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
  at play.api.libs.json.JsObject.as(JsValue.scala:124)
  at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.$anonfun$applyOrElse$1(SlackRtmClient.scala:129)
  at scala.util.Try$.apply(Try.scala:209)
  at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.applyOrElse(SlackRtmClient.scala:129)
  at akka.actor.Actor.aroundReceive(Actor.scala:539)
  at akka.actor.Actor.aroundReceive$(Actor.scala:537)
  at slack.rtm.SlackRtmConnectionActor.aroundReceive(SlackRtmClient.scala:104)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
  at akka.actor.ActorCell.invoke(ActorCell.scala:581)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
  at akka.dispatch.Mailbox.run(Mailbox.scala:229)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
  at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
My guess is that this has something to do with the fact that we have a bought replying to threads, and there is no `user` in the message object, but I can't say for sure.

**Comment by danielvasilev** [comment]
Do you mean `bot` replying (instead of "bought replying")? The bot messages not seem to have the `user` field. Probably need to add support for bot messages.

**Comment by tmbull** [comment]
@danielvasilev Yes, sorry for the spelling error. I did mean that we have a bot generating these messages.

**Comment by danielvasilev** [comment]
The reads path code is `MessageReplied` -> `ReplyMessage`
In `ReplyMessage`  the field is `user` not `username`. The `replies: Seq[ReplyMarker]` would still work since that structure still works.

Either the bot needs to be changed to `user` or the client reads can a new model class to read one with `username`.

What makes more sense. I am not too familiar with the architecture. I am not sure where the bot replies are coming from.

**Comment by tmbull** [comment]
I took a look at the definition of `slackEventReads` (I think this is probably what you're referring to), and I think the assumption made was that `ReplyMessage` would be a standard slack `message` type (and have no subtype). Unfortunately, this assumption is incorrect. Maybe the `ReplyMessage` could be changed to handle the subtype correctly. The issue still stands that a standard message contains a `user` field while a `bot_message` subtype contains a `username` and `bot_id` field, and I'm not sure how best to work around this. I also noticed that there are multiple `// TODO: Message Sub-types` comments in the code, so maybe someone more familiar with those TODOs could chime in.

**Comment by danielvasilev** [comment]
How would you use the `bot message` differently than the regular message? Generally if they are used similarly we can have an abstract class for both so that `ReplyMessage` and `ReplyMessageBot` can inherit from it so that the behaviour of `MessageReplied` is not really changed a lot.

**Comment by tmbull** [comment]
For my use case, I wouldn't use the `bot message` any different at all. I only really care about the`text` field. I just need the deserialization to work. I think that your suggestion for making `ReplyMessage` and `ReplyMessageBot` extend a common abstract class is a good one though. If someone wants to handle the message types differently, they can then case on them.

**Comment by mccartney** [comment]
Thanks for the initial investigation. The whole problem here is that Slack themselves treats these messages differently - as you noticed. The human ones have `user`, the bot ones have `username`. We need some kind of polymorphism here or mapping to complete separate case classes.

We have the same problem already in `Message` vs. `BotMessage` where it has been decided to model it as two separate case classes.
