### ISSUE TITLE
Client is not working in scala 2.13

### ISSUE THREAD

**Issue by acsgh** [slack-scala-client/slack-scala-client#113]
As you can see in Circle CI the integration against the latest scala version is failing:
https://travis-ci.com/slack-scala-client/slack-scala-client/jobs/287982916

This is due the temporal workaround in: https://github.com/slack-scala-client/slack-scala-client/blob/master/src/main/scala/slack/api/SlackApiClient.scala#L31 that seems not to be any longer valid in this version

Do you see any alternative, as it is not possible to initiate a SlackRtmClient client

Stack trace:
`Exception in thread "main" java.lang.ExceptionInInitializerError
	at slack.api.BlockingSlackApiClient.<init>(BlockingSlackApiClient.scala:38)
	at slack.api.BlockingSlackApiClient$.apply(BlockingSlackApiClient.scala:19)
	at slack.rtm.SlackRtmClient.<init>(SlackRtmClient.scala:33)
	at slack.rtm.SlackRtmClient$.apply(SlackRtmClient.scala:24)
	at acsgh.karma.KarmaBot$.delayedEndpoint$acsgh$karma$KarmaBot$1(KarmaBot.scala:15)
	at acsgh.karma.KarmaBot$delayedInit$body.apply(KarmaBot.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at acsgh.karma.KarmaBot$.main(KarmaBot.scala:13)
	at acsgh.karma.KarmaBot.main(KarmaBot.scala)
Caused by: java.lang.IllegalAccessException: Can not set static final akka.parboiled2.CharPredicate field akka.http.impl.model.parser.CharacterClasses$.strict$minusquery$minuschar$minusnp to akka.parboiled2.CharPredicate$MaskBased
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
	at java.base/java.lang.reflect.Field.set(Field.java:780)
	at slack.api.SlackApiClient$.<clinit>(SlackApiClient.scala:38)
	... 18 more
`

**Comment by ni-mi** [comment]
The workaround doesn't seem to work because the field (strict-query-char-np) is being rendered as final in scala 2.13 - and thus it can't be changed.
There is a different work-around to change a final field in java 8 and in later versions - and that is currently what I see as a problem.
@gilbertw1  - I am not sure what the actual workaround is (except that it removes the question mark from `strict-query-char-np`.
Is it possible to fix the issue where it should be fixed - in Akka-http-core?

**Comment by mccartney** [comment]
Thanks for the report.

As far as I understand we use the same Akka version regardless of Scala version. So I am not sure what's the reason for the difference in behavior between Scala versions. The private field which is being read is defined in Akka Http, so I fail to understand why would Scala version change trigger it?

**Comment by mccartney** [comment]
OK. Could it because Scala 2.13 compiles such a line:
https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/model/parser/CharacterClasses.scala#L48
differently to 2.12 by generating the `final` modifier as opposed to previous Scala versions not adding `final` here?

**Comment by mccartney** [comment]
The workaround has been introduced in #60. If I understand it correctly - we could try to remove the workaround and see if the Slack servers accept a question mark (`?`) in the messages we send.

**Comment by mccartney** [comment]
I did that in #117 and it worked.
