### ISSUE TITLE
Repeatedly deriving parse failure errors for 'user_huddle_changed' events

### ISSUE THREAD

**Issue by kiris** [slack-scala-client/slack-scala-client#251]
Other events also generate errors if they are not supported, but the `user_huddle_changed` event in particular was causing repeated errors, so I have raised it as an Issue. 

Error Log
```
[ERROR] [12/05/2022 13:38:18.675] [slack-akka.actor.default-dispatcher-22] [akka://slack/user/$a] [SlackRtmClient] Error reading event: {"type":"user_huddle_changed","user", ...
```

Stack Trace
```
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List(Invalid type property: {}),WrappedArray(user_huddle_changed))))))
        at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
        at play.api.libs.json.JsError.fold(JsResult.scala:66)
        at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
        at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
        at play.api.libs.json.JsObject.as(JsValue.scala:126)
        at slack.rtm.SlackRtmConnectionActor.$anonfun$onTextMessageReceive$1(SlackRtmClient.scala:186)
        at scala.util.Try$.apply(Try.scala:213)
        at slack.rtm.SlackRtmConnectionActor.onTextMessageReceive(SlackRtmClient.scala:186)
        at slack.rtm.SlackRtmConnectionActor$$anonfun$receive$1.applyOrElse(SlackRtmClient.scala:137)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at slack.rtm.SlackRtmConnectionActor.aroundReceive(SlackRtmClient.scala:116)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by mccartney** [comment]
I observe the same.

**Comment by mccartney** [comment]
Thanks for reporting. 

0.4.1 shouldn't have this problem.
