### ISSUE TITLE
A lot of 429 errors occur when connected for a long time

### ISSUE THREAD

**Issue by kiris** [slack-scala-client/slack-scala-client#253]
After being connected to Slack for a long time, at some point I get a lot of 429 errors.

```
[WARN] [12/07/2022 14:01:13.294] [slack-akka.actor.default-dispatcher-19] [RestartWithBackoffSource(akka://slack)] Restarting stream due to failure [1]: slack.api.InvalidResponseError: Bad status code from Slack: 429
slack.api.InvalidResponseError: Bad status code from Slack: 429
        at slack.api.RetryAfter.invalidResponseError(RetryAfter.scala:14)
        at slack.api.SlackApiClient.$anonfun$paginateCollection$3(SlackApiClient.scala:1352)
        at akka.pattern.FutureTimeoutSupport.liftedTree1$1(FutureTimeoutSupport.scala:50)
        at akka.pattern.FutureTimeoutSupport.$anonfun$after$1(FutureTimeoutSupport.scala:50)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:479)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.s^C
```

Before this error occurred, `user_huddle_changed` errors were occurring, so this may be the cause. (ref: #251 )

**Comment by kiris** [comment]
Sorry, this Issue was incorrect. 
My use of Slack APi was not good.
